### ISSUE TITLE
baz calculation has a bug

### ISSUE THREAD

**Issue by chukren** [wjlei1990/pytomo3d#1]
The coordinates of event and receiver are in opposite order, so the back azimuth is actually azimuth.
in pytomo3d/adjoint/adjsrc.py line 203  change
 _, baz, _ = gps2DistAzimuth(elat, elon, slat, slon) 
 to 
 _, baz, _ = gps2DistAzimuth(slat, slon, elat, elon)
should fix the issue

**Comment by wjlei1990** [comment]
My fault. 

I made several mistakes here.

`gps2dist_azimuth(lat1, lon1, lat2, lon2` returns distance_in_m, az, and baz. 

I wil fix it.

**Comment by wjlei1990** [comment]
I fixed it. Could you pull again and let me know if it is fixed?

If so, you can close this issue.

**Comment by chukren** [comment]
done
