### ISSUE TITLE
raise water_level for instrument response removal

### ISSUE THREAD

**Issue by rdno** [wjlei1990/pytomo3d#10]
Hi,

Using the default value for `water_level` (60) in instrument response removal can cause problems as discussed in [obspy#1594](https://github.com/obspy/obspy/issues/1594).

Corresponding lines are in processed.py [L246-L250](https://github.com/wjlei1990/pytomo3d/blob/master/pytomo3d/signal/process.py#L246-L250).

Adding `water_level=100` parameter to the `remove_response` calls solves the issue for my tests.  However, `water_level` value may need to be decided more carefully.

**Comment by wjlei1990** [comment]
So what is your opinion at this point? Should we set the default to 100? So every trace use it?

**Comment by rdno** [comment]
I have seen that `water_level` is a  user parameter now. Maybe we can close this issue.

I think leaving the default as `60` is okay. Because, that is the default value for obspy.

**Comment by wjlei1990** [comment]
fixed
