### ISSUE TITLE
Adjoint source id check 

### ISSUE THREAD

**Issue by chukren** [wjlei1990/pytomo3d#12]
I think the new adjoint source has a default location id "" (null)
https://github.com/wjlei1990/pytomo3d/blob/master/pytomo3d/adjoint/sum_adjoint.py#L129

the check will not let the code proceed because the adj_base.id has default loc_id while adj.id doesn't
https://github.com/wjlei1990/pytomo3d/blob/master/pytomo3d/adjoint/sum_adjoint.py#L29-L31

**Comment by wjlei1990** [comment]
fixed
