### ISSUE TITLE
calculate_adjsrc_on_: window type problem

### ISSUE THREAD

**Issue by mpbl** [wjlei1990/pytomo3d#6]
It seems that:

https://github.com/wjlei1990/pytomo3d/blob/master/pytomo3d/adjoint/adjsrc.py#L137

is not consistent with

https://github.com/wjlei1990/pytomo3d/blob/master/pytomo3d/adjoint/adjsrc.py#L82

`windows`  are different objects in these two functions.

**Comment by wjlei1990** [comment]
Yes, they are.

One is window for the stream, so it is a dict, whose key is the trace id and value is window information.

The other is window for the trace, which only contains the window time information...

**Comment by wjlei1990** [comment]
I have changed the input argument so both functions are in the same fashion. I will modify docstring later on...
